//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfShopADeal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class administra
    {
        public decimal usuario_cedula { get; set; }
        public int tienda_codigo { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual tienda tienda { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
