//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfShopADeal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class cesta
    {
        public int articulo_id { get; set; }
        public int pedido_numpedido { get; set; }
        public int cantidad { get; set; }
        public Nullable<decimal> calificacion { get; set; }
    
        public virtual articulo articulo { get; set; }
        public virtual pedido pedido { get; set; }
    }
}
